fix: prefix incrementor
Uniswap/UniswapX pull request #198
Opened 2023-08-22 03:26 UTC by marktoda

2023-08-22 11:16 UTC, hensha256 commented on test/util/mock/MockFillContractWithOutputOverride.sol
>              for (uint256 j = 0; j < resolvedOrders[i].outputs.length; j++) {
```suggestion
            for (uint256 j = 0; j < resolvedOrders[i].outputs.length; ++j) {
```

2023-08-22 11:16 UTC, hensha256 commented on test/util/mock/MockFillContractWithOutputOverride.sol
>              for (uint256 j = 0; j < resolvedOrders[i].outputs.length; j++) {
i see a few others too - i think you need to search for `j++`

2023-08-22 11:18 UTC, hensha256 requested changes
need to find-and-replace w `j++` too

2023-08-22 21:54 UTC, zhongeric approved these changes

2023-08-25 14:28 UTC, zhongeric approved these changes

2023-12-12 18:10 UTC, closed without merging